[package]
name = "extractbyxpath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"

[dev-dependencies]
assert_cmd = "2"
